import type { Metadata } from 'next'
import './globals.css'
import { Toaster } from 'sonner'

export const metadata: Metadata = {
  title: 'Oaktree App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`antialiased h-[100vh]`}>
        {children}
        <Toaster richColors={true} position="top-right" duration={3000} />
      </body>
    </html>
  )
}
